# golangci-lint configuration for rapidx project
# Replicates GitHub Actions CI checks

run:
  timeout: 5m
  go: "1.24"

linters-settings:
  dupl:
    threshold: 100
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    severity: high
    confidence: high

linters:
  disable-all: true
  enable:
    - dupl
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - goconst
        - dupl
        - gosec
        - whitespace
    - path: testfailures/
      linters:
        - gosec
        - goconst
        - dupl
        - gocyclo
        - whitespace
    - path: docs/examples/
      linters:
        - gosec
        - goconst
        - dupl
        - gocyclo
        - whitespace
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "G115: integer overflow conversion"
      linters:
        - gosec
    - text: "SA9003: empty branch"
      linters:
        - staticcheck
    - text: "cyclomatic complexity.*of func.*is high"
      linters:
        - gocyclo

  max-issues-per-linter: 0
  max-same-issues: 0
  tests: true
  print-linter-name: true
  print-issued-line: true
  colored: true
  skip-dirs:
    - vendor
    - testdata
  use-default-excludes: true